### ISSUE TITLE
Python 3.7 compatibility

### ISSUE THREAD

**Issue by cryzed** [facebookincubator/python-nubia#2]
It would be great if this was fully compatible with Python 3.7, but it unfortunately isn't. The problem seems mostly linked with accessing private members of the `typing`module:

```python-traceback
>>> import nubia
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/.virtualenvs/toolbox/lib/python3.7/site-packages/nubia/__init__.py", line 12, in <module>
    from .internal.deprecation import deprecated
  File "/home/user/.virtualenvs/toolbox/lib/python3.7/site-packages/nubia/internal/deprecation.py", line 15, in <module>
    from nubia.internal.typing import inspect_object
  File "/home/user/.virtualenvs/toolbox/lib/python3.7/site-packages/nubia/internal/typing/__init__.py", line 68, in <module>
    from nubia.internal.helpers import (
  File "/home/user/.virtualenvs/toolbox/lib/python3.7/site-packages/nubia/internal/helpers.py", line 17, in <module>
    from typing import _Union, Any, Iterable  # noqa T484
ImportError: cannot import name '_Union' from 'typing' (/usr/lib/python3.7/typing.py)
```

After importing Union instead (which I'm sure doesn't really fix the problem), it seemingly works fine, however there might be hiding more incompatibilities. For example, I suspect this is one:

```python-traceback
user> pick code=14 stuff=red style=toast                                                                                                      Error: 3
Traceback (most recent call last):
  File "nubia_example.py", line 17, in <module>
    sys.exit(shell.run())
  File "/home/user/.virtualenvs/toolbox/lib/python3.7/site-packages/nubia/internal/nubia.py", line 296, in run
    return self.start_interactive(args)
  File "/home/user/.virtualenvs/toolbox/lib/python3.7/site-packages/nubia/internal/nubia.py", line 196, in start_interactive
    io_loop.run()
  File "/home/user/.virtualenvs/toolbox/lib/python3.7/site-packages/nubia/internal/interactive.py", line 181, in run
    self.parse_and_evaluate(stdout, text)
  File "/home/user/.virtualenvs/toolbox/lib/python3.7/site-packages/nubia/internal/interactive.py", line 127, in parse_and_evaluate
    return self.evaluate_command(stdout, cmd, args, input)
  File "/home/user/.virtualenvs/toolbox/lib/python3.7/site-packages/nubia/internal/interactive.py", line 159, in evaluate_command
    result = cmd_instance.run_interactive(cmd, args, raw)
  File "/home/user/.virtualenvs/toolbox/lib/python3.7/site-packages/nubia/internal/cmdbase.py", line 340, in run_interactive
    new_value = apply_typing(value, target_type)
  File "/home/user/.virtualenvs/toolbox/lib/python3.7/site-packages/nubia/internal/typing/builder.py", line 34, in apply_typing
    return get_typing_function(type)(value)
  File "/home/user/.virtualenvs/toolbox/lib/python3.7/site-packages/nubia/internal/typing/builder.py", line 195, in wrapped
    return function(string, *args_builders)
  File "/usr/lib/python3.7/typing.py", line 668, in __call__
    raise TypeError(f"Type {self._name} cannot be instantiated; "
TypeError: Type List cannot be instantiated; use list() instead
```

**Comment by ylectric** [comment]
Thanks @cryzed for reporting this. Importing `_Union` is an ugly hack that we use for inferring types for optional arguments. I think it's never been tested against Python 3.7, good catch!

**Comment by ylectric** [comment]
@asamolion I think you can start with changing the required Python version in `Pipfile`.

**Comment by asamolion** [comment]
Alright.

**Comment by ylectric** [comment]
@asamolion, sorry for not making it clear enough. Please see my last comment in #6 for more details.
You can use `pipenv install --python 3.7` to use Python 3.7 interpreter with our `Pipfile` (just ignore the warnings).

**Comment by ylectric** [comment]
OK, just for the record: it's tricky. The 3.7 version changes some important bits of typing mechanism which breaks our introspection.

**Comment by calebmarchent** [comment]
Reading the comment, the reference implementation for type inference has been updated to support Python3.7: https://github.com/ilevkivskyi/typing_inspect/commit/7aa7bb5a89ebd584f3885d993b417212592135c0#diff-faac2f2c6bc2bfba052313740ae107e8

The new behaviour is Python version dependent. I think the next action is to integrate the method above into Python-nubia.

**Comment by calebmarchent** [comment]
I have added the port in my 3.7 PR #19; which certainly moved things forward a bit by breaking the failure to import _Union. We then fail on some of the unit tests; which probably means more of the fixes need to be imported.

**Comment by cdluminate** [comment]
Any update on python3.7 compat?

**Comment by calebmarchent** [comment]
No update at present as we are working on other priorities; We would welcome assistance offered in resolving the Python3.7 integration issues.

**Comment by ylectric** [comment]
Hi everyone,
I'm happy to announce that I finished working on Python 3.7 support.

It will take a few days to land it as I'm waiting for #28 and also need to test our internal builds.
