### ISSUE TITLE
Please release latest version

### ISSUE THREAD

**Issue by spencerharmon** [facebookincubator/python-nubia#26]
When running the version in pypi, I get the following error. It only occurs after typing a registered command at the interactive shell and pressing the spacebar.
```
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/sharmon/PycharmProjects/syseng-toolbox-test/venv/lib/python3.6/site-packages/prompt_toolkit/interface.py", line 865, in run
    completions = list(buffer.completer.get_completions(document, complete_event))
  File "/home/sharmon/PycharmProjects/syseng-toolbox-test/venv/lib/python3.6/site-packages/nubia/internal/interactive.py", line 220, in get_completions
    complete_event,
  File "/home/sharmon/PycharmProjects/syseng-toolbox-test/venv/lib/python3.6/site-packages/nubia/internal/cmdbase.py", line 503, in get_completions
    return state_machine.get_completions()
  File "/home/sharmon/PycharmProjects/syseng-toolbox-test/venv/lib/python3.6/site-packages/nubia/internal/completion.py", line 133, in get_completions
    self.doc.text, expect_subcommand=self.cmd.super_command
  File "/home/sharmon/PycharmProjects/syseng-toolbox-test/venv/lib/python3.6/site-packages/nubia/internal/parser.py", line 119, in parse
    partial_result = expected_pattern.parseString(text, parseAll=False)
  File "/home/sharmon/PycharmProjects/syseng-toolbox-test/venv/lib/python3.6/site-packages/pyparsing.py", line 1828, in parseString
    raise exc
  File "/home/sharmon/PycharmProjects/syseng-toolbox-test/venv/lib/python3.6/site-packages/pyparsing.py", line 1818, in parseString
    loc, tokens = self._parse( instring, 0 )
  File "/home/sharmon/PycharmProjects/syseng-toolbox-test/venv/lib/python3.6/site-packages/pyparsing.py", line 1562, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/home/sharmon/PycharmProjects/syseng-toolbox-test/venv/lib/python3.6/site-packages/pyparsing.py", line 3752, in parseImpl
    loc, exprtokens = e._parse( instring, loc, doActions )
  File "/home/sharmon/PycharmProjects/syseng-toolbox-test/venv/lib/python3.6/site-packages/pyparsing.py", line 1562, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/home/sharmon/PycharmProjects/syseng-toolbox-test/venv/lib/python3.6/site-packages/pyparsing.py", line 4098, in parseImpl
    return self.expr._parse( instring, loc, doActions, callPreParse=False )
  File "/home/sharmon/PycharmProjects/syseng-toolbox-test/venv/lib/python3.6/site-packages/pyparsing.py", line 1562, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/home/sharmon/PycharmProjects/syseng-toolbox-test/venv/lib/python3.6/site-packages/pyparsing.py", line 4322, in parseImpl
    loc, tokens = self_expr_parse( instring, loc, doActions, callPreParse=False )
  File "/home/sharmon/PycharmProjects/syseng-toolbox-test/venv/lib/python3.6/site-packages/pyparsing.py", line 1562, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/home/sharmon/PycharmProjects/syseng-toolbox-test/venv/lib/python3.6/site-packages/pyparsing.py", line 4098, in parseImpl
    return self.expr._parse( instring, loc, doActions, callPreParse=False )
  File "/home/sharmon/PycharmProjects/syseng-toolbox-test/venv/lib/python3.6/site-packages/pyparsing.py", line 1562, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/home/sharmon/PycharmProjects/syseng-toolbox-test/venv/lib/python3.6/site-packages/pyparsing.py", line 3735, in parseImpl
    loc, resultlist = self.exprs[0]._parse( instring, loc, doActions, callPreParse=False )
  File "/home/sharmon/PycharmProjects/syseng-toolbox-test/venv/lib/python3.6/site-packages/pyparsing.py", line 1562, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/home/sharmon/PycharmProjects/syseng-toolbox-test/venv/lib/python3.6/site-packages/pyparsing.py", line 2935, in parseImpl
    raise ParseException(instring, loc, self.errmsg, self)

pyparsing.ParseException: Expected W:(ABCD...,ABCD...) (at char 9), (line:1, col:10)
```

It seems to be related to the parsing of the shell text to acquire completion information. It doesn't occur when running from a bash shell and unittests don't have the issue using either using either run_cli_line or run_interactive_line. If I type through the spewing errors at the interactive shell, commands return as expected.

certifi==2019.3.9
chardet==3.0.4
dataclasses==0.6
idna==2.8
pipenv==2018.11.26
pkg-resources==0.0.0
prettytable==0.7.2
prompt-toolkit==1.0.16
Pygments==2.3.1
pyparsing==2.4.0
python-Levenshtein==0.12.0
python-nubia==0.1b4
requests==2.21.0
six==1.12.0
termcolor==1.1.0
urllib3==1.24.1
virtualenv==16.4.3
virtualenv-clone==0.5.3
wcwidth==0.1.7

python 3.6.3
ubuntu 18.10

**Comment by AhmedSoliman** [comment]
This seem to have happened with newer versions of pyparsing. I will take a look at it.

**Comment by spencerharmon** [comment]
Thanks for the help!

**Comment by AhmedSoliman** [comment]
python-nubia 0.1b5 has been released on pypi. Can you please test it and let me know if you still see that issue?

**Comment by spencerharmon** [comment]
Thanks for the help; looks like requirements.txt didn't make it into the package. When installing via pip, I get:
```
  Downloading https://files.pythonhosted.org/packages/f9/22/9f012c6aa84ee53e32460e846a658b145579adc28401ce7762fb3e38a127/python-nubia-0.1b5.tar.gz (45kB)
     |████████████████████████████████| 51kB 3.1MB/s 
    ERROR: Complete output from command python setup.py egg_info:
    ERROR: Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-2u2298ay/python-nubia/setup.py", line 26, in <module>
        with open("requirements.txt", "r") as fd:
      File "/home/sharmon/test/venv/lib/python3.6/codecs.py", line 897, in open
        file = builtins.open(filename, mode, buffering)
    FileNotFoundError: [Errno 2] No such file or directory: 'requirements.txt'
    ----------------------------------------
ERROR: Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-2u2298ay/python-nubia/
```
I downloaded the tarball separately, and it appears that it's missing. Everything works as expected when I install manually from the tarball using the requirements.txt from the github repo, though. That is, when I install from the pypi tarball manually, I don't run into the pyparsing errors like before.

Again, thanks for the help. I'll test out again once requirements.txt is in place for pip.

**Comment by AhmedSoliman** [comment]
Package on pypi has been fixed, will send a PR to ensure that the repo is in-sync with it. @spencerharmon can you verify please?

**Comment by spencerharmon** [comment]
Confirmed. 0.1b6 works as expected.
