### ISSUE TITLE
Nubia crashes when a subcommand has no docstring 

### ISSUE THREAD

**Issue by ylectric** [facebookincubator/python-nubia#44]
After applying the patch from [this gist:](https://gist.github.com/ylectric/87d90a0c4b5fa8d2f38742a228374166)
```
.venv ❯ env PYTHONPATH=(pwd) python example/nubia_example.py super-command do-stuff
Traceback (most recent call last):
  File "example/nubia_example.py", line 17, in <module>
    options=Options(persistent_history=False))
  File "/Users/afomin/github/python-nubia/nubia/internal/nubia.py", line 126, in __init__
    for cmd in self._plugin.get_commands():
  File "/Users/afomin/github/python-nubia/example/nubia_plugin.py", line 51, in get_commands
    AutoCommand(sample_commands.SuperCommand),
  File "/Users/afomin/github/python-nubia/nubia/internal/cmdbase.py", line 172, in __init__
    inspection.command.help
  File "/opt/homebrew/Cellar/python36/3.6.2+_254.20170915/Frameworks/Python.framework/Versions/3.6/lib/python3.6/textwrap.py", line 430, in dedent
    text = _whitespace_only_re.sub('', text)
TypeError: expected string or bytes-like object
```

**Comment by toti1212** [comment]
Hi! Maybe I can help with that. If a subcommand no has description, can be a good approach set as a default description `No description`?

**Comment by toti1212** [comment]
@ylectric it makes sense for you this fix?

**Comment by ylectric** [comment]
Hey @toti1212, I'm really sorry for a delay in response. I'd prefer to avoid having commands without description in the first place and report an error on startup. I'd love to know what @AhmedSoliman thinks.

**Comment by AhmedSoliman** [comment]
I agree with @ylectric here, this is consistent with how we handle normal commands. We require docstrings to load the commands, in case we can't find "docstring" we will log and error and not load the command. We should have the same behaviour for super commands too.

**Comment by toti1212** [comment]
Nice, Maybe I can contribute to that. I will try to do it 🤓
