### ISSUE TITLE
Project status?

### ISSUE THREAD

**Issue by ddutt** [facebookincubator/python-nubia#88]
Hi maintainers,

What is the status of this project? I opened a ticket a while back and I see no response to it. I see the build has been failing since Dec 18, but there's been no fixes. IIRC, I saw an issue filed by Github asking if this project is to be archived due to inactivity. 

Could you please let me know what the status is? This is a useful project to me, and I can fork it and maintain it for my own purposes (I'll keep it open source of course, and do what I can to incorporate requests and fixes).

Thanks,

Dinesh

**Comment by AndreasBackx** [comment]
Thank you for your concern in the status of the project @ddutt. I just want to let you know that we are definitely aware of your concerns and are discussing internally before getting back to you and others about the state of the project and how we plan to move forward.

Let us know if you have any other questions as well and we'll try to discuss and answer them. I hope we can get back to you by next week.

**Comment by ddutt** [comment]
Thanks @AndreasBackx. Looking forward to hearing from you.

**Comment by AndreasBackx** [comment]
Hey @ddutt! I would like to cut the brief silence to ensure that I haven't forgotten about you or Nubia. I was on PTO last week and just want to you know there will be a post here shortly with a summary of the situation and what the future holds. Though I can likely say that the project will be archived one way or another. How we will be doing this and how we could perhaps help you or any users of the project further, is what we hope to make clear in the upcoming post. Again, let me know if there are any questions.

**Comment by ddutt** [comment]
Good day @AndreasBackx As long as you allow us to fork the project and continue independent development, I'm comfortable. I intend to continue working on the project in open source only i.e. expect any changes I make to be public.

**Comment by AndreasBackx** [comment]
Hi @ddut! My apologies for this taking longer than it should. I hope I can outline the process we'd like to go through and hopefully make it as easy as possible for any users to move over to a fork.



1. We won't make a final 0.3.0 release of the project, you're free to distribute this however as part of the first version of your fork. (Though keeping the current license in mind, see below.)
2. The repository and its README will be updated to reflect the state of the project. We can additionally refer to any forks, though we will still distance ourselves from any recommendations on our side as we cannot guarantee their safety and future. They would primarily be a simple gesture to help everything go smoothly on all sides.
3. The project will be archived, made read-only, and transferred to the [Meta Archive](https://github.com/facebookarchive) GitHub organisation. Forks should not be affected from what I understand as GitHub supports transferring projects.
4. The PyPi project would not be transferable out of safety precautions. However, the name Nubia is available for us so you are free to select a PyPi project name similar to "Nubia" or use it elsewhere. (`nubia` as a name seems to be available.) 
5. The forks need to keep the original license in place, though from what I understand any modifications can have their own license as long as the original code is not relicensed and the old license and copyright notices remain. Though I would refer you to reading the license and also referring to some questions asked about this online, I am not a lawyer. 🙁

This process will be started once I have some more time available. Though don't let that keep you from forking.

If you have any more questions, feel free to leave them here. Though if you would like, I can also make myself available for any questions in private as I feel that I can hopefully reply faster to you that way. You can reach out to me on Twitter @AndreasBackx via direct message.

**Comment by ddutt** [comment]
This sounds good @AndreasBackx. I don't see a reason to change the license, at least not for my purposes. Appreciate the tips on the possible names. Given that the UI is more like fish, I might go for a more fishy name :). But maybe not. I'll let you know when we've forked the project and picked a name. Fully understand about not making any recommendations. Makes total sense.

**Comment by AndreasBackx** [comment]
If we were to mention your fork, do know that once the project gets archived, all issues and editing is closed from what I can tell.

Also wanted to note that I've been thinking of bringing the idea of Nubia's interactive shell to other Python CLI libraries like Click and Typer. It might make it easier for users to adopt as they would be familiar with those libraries. Maybe something to think about if you want to continue this idea.

**Comment by ddutt** [comment]
Hi @AndreasBackx I've forked this repo at netenglabs/nubia. Its a public repo and I'll continue to release from there.

**Comment by ddutt** [comment]
I called the python package at PyPi nubia-cli. I've released the 0.1.0 version as is for now.

**Comment by ddutt** [comment]
@AndreasBackx the addition of async has broken everything. Even the example doesn't work if you provide any additional args to  a command. Has this been even tested?

**Comment by ddutt** [comment]
Here is the trace I get:
```
nubia/example on  main [!] via 🐍 v3.8.2 (.venv) took 3m30s 
➜ python nubia_example.py
Logging to /tmp/nubia_example-8_9bc50q
ddutt> lookup hosts='www.google.com'
Traceback (most recent call last):
  File "/home/ddutt/work/nubia/.venv/lib/python3.8/site-packages/prompt_toolkit/eventloop/utils.py", line 116, in get_event_loop
    return getloop()
RuntimeError: no running event loop

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "nubia_example.py", line 27, in <module>
    sys.exit(shell.run())
  File "/home/ddutt/work/nubia/nubia/internal/nubia.py", line 289, in run
    return asyncio.run(self.run_async(cli_args, ipython))
  File "/home/ddutt/.pyenv/versions/3.8.2/lib/python3.8/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "/home/ddutt/.pyenv/versions/3.8.2/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/ddutt/work/nubia/nubia/internal/nubia.py", line 320, in run_async
    return await self.start_interactive(args)
  File "/home/ddutt/work/nubia/nubia/internal/nubia.py", line 168, in start_interactive
    await io_loop.run()
  File "/home/ddutt/work/nubia/nubia/internal/interactive.py", line 151, in run
    text = await prompt.prompt_async(
  File "/home/ddutt/work/nubia/.venv/lib/python3.8/site-packages/prompt_toolkit/shortcuts/prompt.py", line 1208, in prompt_async
    return await self.app.run_async(set_exception_handler=set_exception_handler)
  File "/home/ddutt/work/nubia/.venv/lib/python3.8/site-packages/prompt_toolkit/application/application.py", line 815, in run_async
    return await _run_async2()
  File "/home/ddutt/work/nubia/.venv/lib/python3.8/site-packages/prompt_toolkit/application/application.py", line 797, in _run_async2
    await self.cancel_and_wait_for_background_tasks()
  File "/home/ddutt/work/nubia/.venv/lib/python3.8/site-packages/prompt_toolkit/application/application.py", line 1000, in cancel_and_wait_for_background_tasks
    await task
  File "/home/ddutt/work/nubia/.venv/lib/python3.8/site-packages/prompt_toolkit/buffer.py", line 1909, in new_coroutine
    await coroutine(*a, **kw)
  File "/home/ddutt/work/nubia/.venv/lib/python3.8/site-packages/prompt_toolkit/buffer.py", line 1738, in async_completer
    async for completion in self.completer.get_completions_async(
  File "/home/ddutt/work/nubia/.venv/lib/python3.8/site-packages/prompt_toolkit/completion/base.py", line 271, in get_completions_async
    async for completion in completer.get_completions_async(
  File "/home/ddutt/work/nubia/.venv/lib/python3.8/site-packages/prompt_toolkit/completion/base.py", line 227, in get_completions_async
    async for completion in generator_to_async_generator(
  File "/home/ddutt/work/nubia/.venv/lib/python3.8/site-packages/prompt_toolkit/eventloop/async_generator.py", line 74, in generator_to_async_generator
    await runner_f
  File "/home/ddutt/.pyenv/versions/3.8.2/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/ddutt/work/nubia/.venv/lib/python3.8/site-packages/prompt_toolkit/eventloop/async_generator.py", line 43, in runner
    for item in get_iterable():
  File "/home/ddutt/work/nubia/.venv/lib/python3.8/site-packages/prompt_toolkit/completion/base.py", line 228, in <lambda>
    lambda: self.completer.get_completions(document, complete_event)
  File "/home/ddutt/work/nubia/nubia/internal/interactive.py", line 193, in get_completions
    return cmd_instance.get_completions(
  File "/home/ddutt/work/nubia/nubia/internal/cmdbase.py", line 518, in get_completions
    return state_machine.get_completions()
  File "/home/ddutt/work/nubia/nubia/internal/completion.py", line 143, in get_completions
    if self.doc.char_before_cursor in " ]}":
  File "/home/ddutt/work/nubia/nubia/internal/completion.py", line 143, in get_completions
    if self.doc.char_before_cursor in " ]}":
  File "/home/ddutt/work/nubia/.venv/lib/python3.8/site-packages/prompt_toolkit/application/application.py", line 957, in trace_dispatch
    with app.input.detach():
  File "/home/ddutt/.pyenv/versions/3.8.2/lib/python3.8/contextlib.py", line 113, in __enter__
    return next(self.gen)
  File "/home/ddutt/work/nubia/.venv/lib/python3.8/site-packages/prompt_toolkit/input/vt100.py", line 189, in _detached_input
    loop = get_event_loop()
  File "/home/ddutt/work/nubia/.venv/lib/python3.8/site-packages/prompt_toolkit/eventloop/utils.py", line 118, in get_event_loop
    return asyncio.get_event_loop_policy().get_event_loop()
  File "/home/ddutt/.pyenv/versions/3.8.2/lib/python3.8/asyncio/events.py", line 639, in get_event_loop
    raise RuntimeError('There is no current event loop in thread %r.'
RuntimeError: There is no current event loop in thread 'ThreadPoolExecutor-0_0'.
```

**Comment by ddutt** [comment]
Ignore my comments, it was my mistake.
