### ISSUE TITLE
There is a problem with the example

### ISSUE THREAD

**Issue by tlmn-local** [facebookincubator/python-nubia#89]
```
python3 -m pip install python-nubia
cd example

python3 -m nubia_example
```

result
```
/usr/local/lib/python3.9/site-packages/nubia/internal/nubia.py:203: RuntimeWarning: coroutine 'NubiaExampleContext.on_interactive' was never awaited
  self._ctx.on_interactive(args)
RuntimeWarning: Enable tracemalloc to get the object allocation traceback

Unhandled exception in event loop:
  File "/usr/local/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/local/lib/python3.9/site-packages/prompt_toolkit/eventloop/utils.py", line 75, in schedule
    func()
  File "/usr/local/lib/python3.9/site-packages/prompt_toolkit/application/application.py", line 484, in redraw
    self._redraw()
  File "/usr/local/lib/python3.9/site-packages/prompt_toolkit/application/application.py", line 556, in _redraw
    self.context.copy().run(run_in_context)
  File "/usr/local/lib/python3.9/site-packages/prompt_toolkit/application/application.py", line 539, in run_in_context
    self.renderer.render(self, self.layout)
  File "/usr/local/lib/python3.9/site-packages/prompt_toolkit/renderer.py", line 642, in render
    layout.container.preferred_height(size.columns, size.rows).preferred,
  File "/usr/local/lib/python3.9/site-packages/prompt_toolkit/layout/containers.py", line 326, in preferred_height
    dimensions = [
  File "/usr/local/lib/python3.9/site-packages/prompt_toolkit/layout/containers.py", line 327, in <listcomp>
    c.preferred_height(width, max_available_height) for c in self._all_children
  File "/usr/local/lib/python3.9/site-packages/prompt_toolkit/layout/containers.py", line 2643, in preferred_height
    return self.content.preferred_height(width, max_available_height)
  File "/usr/local/lib/python3.9/site-packages/prompt_toolkit/layout/containers.py", line 1624, in preferred_height
    return self._merge_dimensions(
  File "/usr/local/lib/python3.9/site-packages/prompt_toolkit/layout/containers.py", line 1652, in _merge_dimensions
    preferred = get_preferred()
  File "/usr/local/lib/python3.9/site-packages/prompt_toolkit/layout/containers.py", line 1617, in preferred_content_height
    return self.content.preferred_height(
  File "/usr/local/lib/python3.9/site-packages/prompt_toolkit/layout/controls.py", line 370, in preferred_height
    content = self.create_content(width, None)
  File "/usr/local/lib/python3.9/site-packages/prompt_toolkit/layout/controls.py", line 383, in create_content
    fragments_with_mouse_handlers = self._get_formatted_text_cached()
  File "/usr/local/lib/python3.9/site-packages/prompt_toolkit/layout/controls.py", line 347, in _get_formatted_text_cached
    return self._fragment_cache.get(
  File "/usr/local/lib/python3.9/site-packages/prompt_toolkit/cache.py", line 41, in get
    value = getter_func()
  File "/usr/local/lib/python3.9/site-packages/prompt_toolkit/layout/controls.py", line 348, in <lambda>
    get_app().render_counter, lambda: to_formatted_text(self.text, self.style)
  File "/usr/local/lib/python3.9/site-packages/prompt_toolkit/formatted_text/base.py", line 79, in to_formatted_text
    return to_formatted_text(value(), style=style)
  File "/usr/local/lib/python3.9/site-packages/prompt_toolkit/formatted_text/base.py", line 79, in to_formatted_text
    return to_formatted_text(value(), style=style)
  File "/usr/local/lib/python3.9/site-packages/nubia/internal/interactive.py", line 81, in _get_bottom_toolbar
    return PygmentsTokens(self._status_bar.get_tokens())
  File "/Users/zero/python-nubia/example/nubia_statusbar.py", line 29, in get_tokens
    if context.get_context().verbose:

Exception 'NubiaExampleContext' object has no attribute 'verbose'
Press ENTER to continue...

Unhandled exception in event loop:
  File "/usr/local/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/local/lib/python3.9/site-packages/prompt_toolkit/eventloop/utils.py", line 75, in schedule
    func()
  File "/usr/local/lib/python3.9/site-packages/prompt_toolkit/application/application.py", line 484, in redraw
    self._redraw()
  File "/usr/local/lib/python3.9/site-packages/prompt_toolkit/application/application.py", line 556, in _redraw
    self.context.copy().run(run_in_context)
  File "/usr/local/lib/python3.9/site-packages/prompt_toolkit/application/application.py", line 539, in run_in_context
    self.renderer.render(self, self.layout)
  File "/usr/local/lib/python3.9/site-packages/prompt_toolkit/renderer.py", line 642, in render
    layout.container.preferred_height(size.columns, size.rows).preferred,
  File "/usr/local/lib/python3.9/site-packages/prompt_toolkit/layout/containers.py", line 326, in preferred_height
    dimensions = [
  File "/usr/local/lib/python3.9/site-packages/prompt_toolkit/layout/containers.py", line 327, in <listcomp>
    c.preferred_height(width, max_available_height) for c in self._all_children
  File "/usr/local/lib/python3.9/site-packages/prompt_toolkit/layout/containers.py", line 2643, in preferred_height
    return self.content.preferred_height(width, max_available_height)
  File "/usr/local/lib/python3.9/site-packages/prompt_toolkit/layout/containers.py", line 1624, in preferred_height
    return self._merge_dimensions(
  File "/usr/local/lib/python3.9/site-packages/prompt_toolkit/layout/containers.py", line 1652, in _merge_dimensions
    preferred = get_preferred()
  File "/usr/local/lib/python3.9/site-packages/prompt_toolkit/layout/containers.py", line 1617, in preferred_content_height
    return self.content.preferred_height(
  File "/usr/local/lib/python3.9/site-packages/prompt_toolkit/layout/controls.py", line 370, in preferred_height
    content = self.create_content(width, None)
  File "/usr/local/lib/python3.9/site-packages/prompt_toolkit/layout/controls.py", line 383, in create_content
    fragments_with_mouse_handlers = self._get_formatted_text_cached()
  File "/usr/local/lib/python3.9/site-packages/prompt_toolkit/layout/controls.py", line 347, in _get_formatted_text_cached
    return self._fragment_cache.get(
  File "/usr/local/lib/python3.9/site-packages/prompt_toolkit/cache.py", line 41, in get
    value = getter_func()
  File "/usr/local/lib/python3.9/site-packages/prompt_toolkit/layout/controls.py", line 348, in <lambda>
    get_app().render_counter, lambda: to_formatted_text(self.text, self.style)
  File "/usr/local/lib/python3.9/site-packages/prompt_toolkit/formatted_text/base.py", line 79, in to_formatted_text
    return to_formatted_text(value(), style=style)
  File "/usr/local/lib/python3.9/site-packages/prompt_toolkit/formatted_text/base.py", line 79, in to_formatted_text
    return to_formatted_text(value(), style=style)
  File "/usr/local/lib/python3.9/site-packages/nubia/internal/interactive.py", line 81, in _get_bottom_toolbar
    return PygmentsTokens(self._status_bar.get_tokens())
  File "/Users/zero/python-nubia/example/nubia_statusbar.py", line 29, in get_tokens
    if context.get_context().verbose:

Exception 'NubiaExampleContext' object has no attribute 'verbose'
Press ENTER to continue...
zero> Traceback (most recent call last):
  File "/usr/local/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/zero/python-nubia/example/nubia_example.py", line 27, in <module>
    sys.exit(shell.run())
  File "/usr/local/lib/python3.9/site-packages/nubia/internal/nubia.py", line 312, in run
    return self.start_interactive(args)
  File "/usr/local/lib/python3.9/site-packages/nubia/internal/nubia.py", line 212, in start_interactive
    io_loop.run()
  File "/usr/local/lib/python3.9/site-packages/nubia/internal/interactive.py", line 147, in run
    text = prompt.prompt(
  File "/usr/local/lib/python3.9/site-packages/prompt_toolkit/shortcuts/prompt.py", line 1033, in prompt
    return self.app.run(
  File "/usr/local/lib/python3.9/site-packages/prompt_toolkit/application/application.py", line 937, in run
    return loop.run_until_complete(
  File "/usr/local/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.9/site-packages/prompt_toolkit/application/application.py", line 664, in run_async
    assert not self._is_running, "Application is already running."
AssertionError: Application is already running.
```

Is there a problem with my method of operation?

**Comment by eubnara** [comment]
@tlmn-local 
I think the nubia version on pip is not matched the source version.
You could try to build from source (https://github.com/facebookincubator/python-nubia#building-nubia-from-source) and install with `.whl` file.

```
poetry build
pip install dist/python_nubia-0.3.0-py3-none-any.whl
```

After that, execute the example.
```
python -m nubia_example
```

**Comment by AndreasBackx** [comment]
Please see #88 for context. The main branch has version 0.3.0 which has not been released and will not be released as the project is getting archived.
